baseURL = "https://jorgefelipe.info"
languageCode = 'en-us'
title = 'Jorge Felipe'
theme = 'hugo-noir'
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# URL handling
relativeURLs = true
canonifyURLs = true

# Taxonomy configuration
[taxonomies]
  category = "categories"
  tag = "tags"

[markup.highlight]
style = "dracula"

[params]
name = "Jorge Felipe"
location = "SÃ£o paulo, Brazil"
description = "Full-stack software engineer focused on developing scalable web applications and supporting open-source initiatives. Currently expanding my expertise in back-end technologies and studying COBOL."
# profile_image = "/images/profile.jpg"
discord = ""
github = "https://github.com/livehass"
github_username = "livehass"
# email = ""
# twitter = ""
# twitter_username = ""
# medium = ""
# linkedin = "https://www.linkedin.com/in/felipesiper/"
# linkedin_username = "felipesiper"
# instagram = ""
# leetcode = ""
# leetcode_username = ""
# monkeytype = ""
# monkeytype_username = ""
# kaggle = ""
# kaggle_username = ""

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

    